### ISSUE TITLE
Statically linking with cgo

### ISSUE THREAD

**Issue by sulimma** [cronologic-de/xhptdc8_babel#27]
@Bassem-Ramzy : 

This should work in principle:
```Go
//#cgo CFLAGS: -g -Wall
//#cgo LDFLAGS: -lxhptdc8_driver_64
//#include "xHPTDC8_interface.h"
import "C"

import "fmt"

func main() {
    init_parameters = C.struct_xhptdc8_manager_init_parameters
    fmt.Println(init_parameters)
    error_code := C.xhptdc8_get_default_init_parameters(&init_parameters)
    fmt.Println(error_code)
    fmt.Println(init_parameters)
}
```` 

However, we need the library as a file of type `.a` as gcc can't link .dlls.

See: 
https://stackoverflow.com/questions/65259409/using-a-windows-dll-in-go-with-cgo
https://cygwin.com/cygwin-ug-net/dll.html

Apparantly if you have gcc properly installed you should be able to create the library with 
```BASH
echo EXPORTS > foo.def
nm foo.dll | grep ' T _' | sed 's/.* T _//' >> foo.def
dlltool -dllname lxhptdc8_driver_64.dll --def lxhptdc8_driver_64.def --output-lib lxhptdc8_driver_64.a
```

I did not test this as my gcc is running fine under WSL but I don't have a working GCC setup for windows.

**Comment by Bassem-Ramzy** [comment]
The following code works well:

```Go
package main

/*
	#cgo CFLAGS:  -Wall -g -I../../../lib/include/
	#cgo LDFLAGS: -static -L./ -l:xhptdc8_driver_64.lib
	#include "xhptdc8_interface.h"
*/
import "C"
import (
	"encoding/json"
	"fmt"
	"log"
	"os"
)

func main() {
	init_parameters := C.struct_xhptdc8_manager_init_parameters_t{}
	error_code := C.xhptdc8_get_default_init_parameters(&init_parameters)
	fmt.Println(error_code)

	out1, err1 := json.MarshalIndent(init_parameters, "", "  ")
	if err1 != nil {
		log.Println(err1)
		os.Exit(1)
	}
	fmt.Println(string(out1))
}
```

With output  
```
0
{
  "Version": 1,
  "Variant": 0
}
```
Those are the only two members that have initials in capital letters in the structure, for testing purpose.

Also, `.a` results in the same output, when we replace:
```Go
	#cgo LDFLAGS: -static -L./ -l:xhptdc8_driver_64.lib
```

with
```Go
	#cgo LDFLAGS: -static -L./ -l:xhptdc8_driver_64.a
```

By the way, `.def` and `.lib` both work fine.

With the following **updates in xHPTDC8_interface.h**:
1. Structure elements starts in upper case letters for `MarshalIndent` to display them properly. We can define them in Go files (already done with the dynamically linked Go code), or to create an identical header with this update in variables names to be imported by Go. 
2. With `= -1` commented in (can do more investigation on that)
```C
	XHPTDC8_API const char* xhptdc8_get_last_error_message(xhptdc8_manager hMgr, int index/* = -1*/);
```

@sulimma Thus, we now can statically call/use driver APIs and structures, with an only condition which is to **have xhptdc8_driver_64.dll in the same execution folder** in order to be able to to run xhptdc8_info.exe, _that's OK, right?_
For cross-platform, we can similarly have .so with the .a for Linux for instance.

**Comment by sulimma** [comment]
Please create an alternate haeder file for go and then proceed to simplify the code of the info tool as much as possible. It appears that you can get rid of most of the wrapper code.

**Comment by sulimma** [comment]
I asked around among my coder friends and one very experienced programmer without any Go knowledge googled this:

go build --tags netgo --ldflags '-extldflags "-lm -lstdc++ -static"'

siehe folgende Links:
https://blog.hashbangbash.com/2014/04/linking-golang-statically/
https://medium.com/@diogok/on-golang-static-binaries-cross-compiling-and-plugins-1aed33499671
https://www.arp242.net/static-go.html
https://stackoverflow.com/questions/37630274/what-do-these-go-build-flags-mean-netgo-extldflags-lm-lstdc-static

**Comment by Bassem-Ramzy** [comment]
> Please create an alternate haeder file for go and then proceed to simplify the code of the info tool as much as possible. It appears that you can get rid of most of the wrapper code.

After a little research and trials, it turned out that we don't need a new header, Go can cast the C.struct_xxx to Go struct easily and perfectly. All structures are defined in Go with variables names start in capital letters as designed.

**Comment by Bassem-Ramzy** [comment]
> I asked around among my coder friends and one very experienced programmer without any Go knowledge googled this:
> 
> go build --tags netgo --ldflags '-extldflags "-lm -lstdc++ -static"'
> 
> siehe folgende Links:
> https://blog.hashbangbash.com/2014/04/linking-golang-statically/
> https://medium.com/@diogok/on-golang-static-binaries-cross-compiling-and-plugins-1aed33499671
> https://www.arp242.net/static-go.html
> https://stackoverflow.com/questions/37630274/what-do-these-go-build-flags-mean-netgo-extldflags-lm-lstdc-static

Excellent articles indeed, I'm already using pieces of each
```CMD
go build -v -x -ldflags  '-extldflags "-static"' .\xhptdc8_info.go .\info_aux.go
```
with code:
```Go
/*
	#cgo CFLAGS:  -Wall -g -I../../../../lib/include/
	#cgo LDFLAGS: -static -L./ -l:../xhptdc8_driver_64.lib
	#include "xhptdc8_interface.h"
*/
import "C"
```

The DLL is statically linked in the way that: after building info.exe with that command with DLL function V1.0, if DLL is changed to V1.1 and copied to the same folder with info.exe, then info.exe still executes V1.0. However, if there is no DLL in the path with info.exe, it doesn't crash but it does nothing.

Still have other options that need further research:
1. Compiling the Dummy Library code (.cpp files) with Go. But in this case, we will need to have two versions of Go build (Driver & Dummy), and new build with every change in each. This option is the most making sense option, since it follows the "static" definition, which contradicts with using D _ynamic_ LL by nature.
2. Using `gccgo` compiler
```CMD
go build -compiler gccgo --gccgoflags "-static" ./code-cgo.go
```
3. Use go tool arguments like
```CMD
 '-extldflags "-lm -lstdc++ -static"'
```
But, using:
```CMD
go build --tags netgo --ldflags '-extldflags " -l:xhptdc8_driver_64.lib -static"' .\xhptdc8_info.go .\info_aux.go
```
We get:
```CMD
flag provided but not defined: -l:xhptdc8_driver_64.lib
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
```
 ---
My opinion is that we have Go code calling native C functions & structures in _a simple way_, having the DLL with the exe in the folder is not a big issue and is normal and "dynamic" (replacing DLL with newer _compatible_ versions doesn't need rebuild). 
We are cool without static build, until it is a solution to a problem we have.

**Comment by sulimma** [comment]
OK. Then we leave it as it is.
The dll is install in C:\program files\cronologic\xhptdc8\lib
on every computer that the driver is installed.
Is it possible to use it from that location? E.g. by a symbolic link or a search path environment variable?

**Comment by Bassem-Ramzy** [comment]
Yes, as long as the DLL is on the %PATH% then info.exe should find it

**Comment by Bassem-Ramzy** [comment]
For the record, those are some of my tests with the results:
1. That causes no error  but still needs DLL
```CMD
\dummy> dlltool -dllname ./msvscpp/x64/debug/xhptdc8_driver_64.dll --def ./xhptdc8_driver_64.def --output-lib xhptdc8_driver_64.a
\util\info\src-cgo> go build .\xhptdc8_info.go
```

2. That causes no error when removing the DLL but doesn't display the struct, but when it's back, it displays the struct
```CMD
\util\info\src-cgo> go build -ldflags "-linkmode external -extldflags -static" .\xhptdc8_info.go
```
From [this link](https://stackoverflow.com/questions/16747021/how-do-you-statically-link-a-c-library-in-go-using-cgo
)

3. That causes no error when removing the DLL but doesn't display the struct nor (exit status 3221225781), but when it's back, it displays the struct
```CMD
\dummy> gcc -Wall -c xHPTDC8_dummy_interface.cpp ./msvscpp/msvscpp/pch.cpp ./msvscpp/msvscpp/dllmain.cpp -static -I./msvscpp/msvscpp -I../lib/include
\dummy> ar -rcs xhptdc8_driver_64.a .\dllmain.o .\pch.o .\xHPTDC8_dummy_interface.o
\util\info\src-cgo> go build -ldflags "-linkmode external -extldflags -static" .\xhptdc8_info.go
```
